### ISSUE TITLE
If you go straight from open cart to clicking an add to cart button, it adds the item to the cart but closes the cart

### ISSUE THREAD

**Issue by ghost** [lilygdu/TH-starter#159]
![image](https://user-images.githubusercontent.com/77162982/111700249-814b1300-880f-11eb-9d72-3be6272e7319.png)

**Comment by lilygdu** [comment]
https://user-images.githubusercontent.com/77121299/111731816-7c975680-8831-11eb-8558-ea33e54e3a42.mov

**Comment by andyweiss1982** [comment]
I _think_ this would be fixed by adding the `add-to-order` class on that button, like we do here;

https://github.com/lilygdu/TH-starter/blob/9dbfb30b5d0d208fe46ac1f6052722b5494e75eb/public/components/Item.js#L109-L119

Because of this code here:

https://github.com/lilygdu/TH-starter/blob/9dbfb30b5d0d208fe46ac1f6052722b5494e75eb/public/components/Cart.js#L141-L146
